name: efood_kitchen
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.1+2

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.6
  intl: any
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^12.0.3
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  country_code_picker: ^3.0.0
  vibration: ^1.7.4-nullsafety.0
  shimmer: ^2.0.0-nullsafety.0
  flutter_custom_clippers: ^2.0.0
  flutter_spinkit: ^5.1.0
  audioplayers: ^0.20.1
  http: ^0.13.5
  permission_handler: ^10.2.0
  logger: ^2.0.2+1
  hive: ^2.2.3
  hive_flutter:
  hive_generator: ^2.0.1
  gap:
  flutter_ringtone_player: ^3.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  build_runner:
flutter_icons:
  image_path: "assets/image/logo.png"
  image_path_ios: "assets/image/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900